# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/salim.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# salim: A Wild Mix of Functions Serving Various Purposes
# Copyright (C) 2022 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

utils::globalVariables(names = c(".",
                                 "download_url",
                                 "filename",
                                 "id",
                                 "name",
                                 "version_nr"))

pkg_mgr_hint <- function(software = names(pkg_mgr_software)) {
  
  software <- rlang::arg_match(software)
  
  result <- ""
  
  if (xfun::is_macos()) {
    result %<>% paste0(pkg_mgr_prose(software = software,
                                     pkg_mgrs = "brew"))
    
  } else if (xfun::is_windows()) {
    result %<>% paste0(pkg_mgr_prose(software = software,
                                     pkg_mgrs = c("scoop", "choco")))
  }
  
  result
}

pkg_mgr_prose <- function(software,
                          pkg_mgrs = c("brew", "scoop", "choco")) {
  pkg_mgr_names <-
    pkg_mgrs %>%
    dplyr::recode(brew = "Homebrew",
                  scoop = "Scoop",
                  choco = "Chocolatey")
  
  pkg_mgr_software %>%
    purrr::chuck(software) %>%
    pal::list_keep(keep = pkg_mgrs) %>%
    purrr::map2_chr(.y = pkg_mgr_names,
                    .f = ~ paste0(.y, " ({.code ", .x$cmd, "})")) %>%
    pal::prose_ls(last_sep = " or ") %>%
    purrr::when(length(.) > 0L ~ paste0(" ", software, " is also available via ", ., "."),
                ~ "")
}

#' Prettify date
#'
#' @description
#' `r lifecycle::badge("deprecated")`
#' 
#' Use [stringi::stri_datetime_format()] instead:
#' 
#' ```r
#' stringi::stri_datetime_format(format = c("date_short", "date_medium", "date_long", "date_full"),
#'                               locale = "en")
#' ```
#'
#' @details
#' Note that this might only work on (Ubuntu) Linux in the current form since locales are one bitchy hell of a PITA...
#'
#' @param date Date to be prettified. A [date][base::Date] or something coercible to.
#' @param locale Locale the date should be prettified for. Currently only `"en"`/`"en-US"` and `"de"`/`"de-CH"` are implemented.
#'
#' @return A character scalar.
#' @family spoken
#' @keywords internal
#'
#' @examples
#' salim:::prettify_date("2021-12-21")
prettify_date <- function(date,
                          locale = c("en", "de", "en-US", "de-CH")) {

  lifecycle::deprecate_warn(when = "0.0.9015",
                            what = "prettify_date()",
                            details = paste0('Use the more powerful and more robust `stringi::stri_datetime_format(format = c("date_short", "date_medium", ',
                                             '"date_long", "date_full"), locale = "en")` function instead.'))
  
  locale <- rlang::arg_match(locale)

  withr::with_locale(new = c("LC_TIME" = purrr::when(. = locale,
                                                     . %in% c("en", "en-US") ~ "C",
                                                     . %in% c("de", "de-CH") ~ "de_CH.utf8")),
                     code =
                       locale %>%
                       purrr::when(. %in% c("en", "en-US") ~
                                     "%B %d, %Y",
                                   . %in% c("de", "de-CH") ~
                                     "%d. %B %Y",
                                   ~ cli::cli_abort("Specified {.arg locale} not implemented yet.")) %>%
                       format(x = lubridate::as_date(date)))
}

#' Prettify datetime
#'
#' @description
#' `r lifecycle::badge("deprecated")`
#' 
#' Use [stringi::stri_datetime_format()] instead:
#' 
#' ```r
#' stringi::stri_datetime_format(format = c("datetime_short", "datetime_medium", "datetime_long", "datetime_full"),
#'                               locale = "en")
#' ```
#'
#' @details
#' Note that this might only work on (Ubuntu) Linux in the current form since locales are one bitchy hell of a PITA...
#'
#' @param datetime Datetime to be prettified. A [datetime][base::DateTimeClasses] or something coercible to.
#' @param locale Locale the datetime should be prettified for. Currently only `"en"`/`"en-US"` and `"de"`/`"de-CH"` are implemented.
#'
#' @return A character scalar.
#' @family spoken
#' @keywords internal
#'
#' @examples
#' salim:::prettify_datetime("2021-12-21T00:00:01Z")
prettify_datetime <- function(datetime,
                              locale = c("en", "de", "en-US", "de-CH")) {

  lifecycle::deprecate_warn(when = "0.0.9015",
                            what = "prettify_datetime()",
                            details = paste0('Use the more powerful and more robust `stringi::stri_datetime_format(format = c("datetime_short", ',
                                             '"datetime_medium", "datetime_long", "datetime_full"), locale = "en")` function instead.'))

  locale <- rlang::arg_match(locale)

  withr::with_locale(new = c("LC_TIME" = purrr::when(. = locale,
                                                     . %in% c("en", "en-US") ~ "C",
                                                     . %in% c("de", "de-CH") ~ "de_CH.utf8")),
                     code =
                       locale %>%
                       purrr::when(. %in% c("en", "en-US") ~
                                     "%B %d, %Y, %I:%M %p",
                                   . %in% c("de", "de-CH") ~
                                     "%d. %B %Y, %H:%M Uhr",
                                   ~ cli::cli_abort("Specified {.arg locale} not implemented yet.")) %>%
                       format(x = lubridate::as_datetime(datetime)))
}

#' Convert an integer into spelled abbreviated English or German rank
#'
#' @param x An integer scalar or something coercible to.
#' @param lang The language to write the rank in.
#'
#' @return A character scalar.
#' @family spoken
#' @export
rank_nr <- function(x,
                    lang = c("en", "de")) {
  
  lang <- rlang::arg_match(lang)
  result <- "?"
  
  if (length(x) > 0L) {
    
    if (lang == "de") {
      result <- switch(EXPR = as.character(as.integer(x)),
                       "1" = "erste",
                       "2" = "zweite",
                       "3" = "dritte",
                       "4" = "vierte",
                       "5" = "f\u00fcnfte",
                       "6" = "sechste",
                       "7" = "siebte",
                       "8" = "achte",
                       "9" = "neunte",
                       "?")
      
    } else if (lang == "en") {
      result <- switch(EXPR = as.character(as.integer(x)),
                       "1" = "1st",
                       "2" = "2nd",
                       "3" = "3rd",
                       "4" = "4th",
                       "5" = "5th",
                       "6" = "6th",
                       "7" = "7th",
                       "8" = "8th",
                       "9" = "9th",
                       "?")
    }
  }
  
  result
}

#' Write out a count
#'
#' @param n The count to write out in letters. A non-negative integer scalar.
#' @param lang The language to write out `n` in.
#' @param use_singular Use a definite descriptor for `n = 0` and `n = 1` instead of the indistinct number. A logical scalar.
#' @param use_dual Use a definite descriptor for `n = 2` instead of the indistinct number. A logical scalar.
#' @param strip_article Strip the definite article from the definite descriptors. Only relevant if at least one of `use_singular` or `use_dual` is `TRUE`. A
#'   logical scalar.
#'
#' @return A character scalar.
#' @family spoken
#' @export
write_out_n <- function(n,
                        lang = c("en", "de"),
                        use_singular = FALSE,
                        use_dual = FALSE,
                        strip_article = use_dual) {
  
  n %<>% checkmate::assert_count() %>% as.character()
  lang <- rlang::arg_match(lang)
  checkmate::assert_flag(use_singular)
  checkmate::assert_flag(use_dual)
  checkmate::assert_flag(strip_article)
  
  if (lang == "en") {
    
    result <- switch(EXPR = n,
                     `0` = ifelse(use_singular,
                                  "no",
                                  "zero"),
                     `1` = ifelse(use_singular,
                                  "the",
                                  "one"),
                     `2` = ifelse(use_dual,
                                  "the two",
                                  "two"),
                     xfun::numbers_to_words(as.integer(n)))
    
  } else if (lang == "de") {
    
    result <- switch(EXPR = n,
                     `0` = ifelse(use_singular,
                                  "keine",
                                  "null"),
                     `1` = ifelse(use_singular,
                                  "die",
                                  "ein"),
                     `2` = ifelse(use_dual,
                                  "die beiden",
                                  "zwei"),
                     `3` = "drei",
                     `4` = "vier",
                     `5` = "f\u00fcnf",
                     `6` = "sechs",
                     `7` = "sieben",
                     `8` = "acht",
                     `9` = "neun")
  }
  
  result %>% purrr::when(strip_article ~ stringr::str_remove(string = .,
                                                             pattern = switch(EXPR = lang,
                                                                              de = "^[Dd]ie ?",
                                                                              en = "^[Tt]he ?")),
                         ~ .)
}

#' Append `"n"` to indefinite article where indicated
#'
#' Appends an `"n"` to the indefinite article "a" if required by English language rules.
#'
#' Note that this function only covers part of all cases where "an" instead of "a" is indicated. Since the choice of _a_ or _an_ [depends on sound, not 
#' spelling](http://www.butte.edu/departments/cas/tipsheets/grammar/articles.html), it's not trivial to implement a universal solution.
#'
#' For example, this function doesn't properly append an `"n"` to the indefinite article in the following situations:
#' - A word starting with the letter "u" where it is pronounced as a vowel, e.g. _**unhappy**_. Note that most English words starting with letter "u" are
#'   pronounced differently like _universum_ and thus require the indefinite article _a_, not _an_.
#' - A word starting with a consonant that is pronounced as a vowel, e.g. _**hour**_.
#'
#' @param x A character vector.
#'
#' @return A character vector.
#' @family spoken
#' @export
#'
#' @examples
#' n_ify("This is a absolute disaster, such a error.")
n_ify <- function(x) {
  
  purrr::map_chr(.x = x,
                 .f = stringr::str_replace_all,
                 pattern = "(^[Aa]| a)(?= [AaEeOoIi]\\w+)",
                 replacement = "\\1n")
}

#' Get the German definite article
#'
#' @param gender The grammatical gender of the subject the definite article refers to.
#' @param case The grammatical case of the subject the definite article refers to.
#' @param pluralize Whether to return the plural form of the definite article. A logical scalar.
#'
#' @return A character scalar.
#' @family spoken
#' @export
definite_article_de <- function(gender = c("feminine",
                                           "masculine",
                                           "neuter"),
                                case = c("nominative",
                                         "genitive",
                                         "dative",
                                         "accusative"),
                                pluralize = FALSE) {
  
  gender <- rlang::arg_match(gender)
  case <- rlang::arg_match(case)
  
  if (checkmate::assert_flag(pluralize)) {
    
    switch(EXPR = case,
           nominative = "die",
           genitive = "der",
           dative = "den",
           accusative = "die")
    
  } else {
    
    switch(EXPR = case,
           nominative = switch(EXPR = gender,
                               feminine = "die",
                               masculine = "der",
                               neuter = "das"),
           genitive = switch(EXPR = gender,
                             feminine = "der",
                             "des"),
           dative = switch(EXPR = gender,
                           feminine = "der",
                           "dem"),
           accusative = switch(EXPR = gender,
                               feminine = "die",
                               masculine = "den",
                               neuter = "das"))
  }
}

#' Decline the German definite article
#'
#' The declination of the German definite article [is a relative pronoun](https://de.wikipedia.org/wiki/Relativpronomen#Der,_die,_das).
#'
#' Note that the second singular feminine and plural genitive form `"derer"` is ignored by this function.
#'
#' @inheritParams definite_article_de
#'
#' @inherit definite_article_de return
#' @family spoken
#' @export
definite_article_de_declined <- function(gender = c("feminine",
                                                    "masculine",
                                                    "neuter"),
                                         case = c("nominative",
                                                  "genitive",
                                                  "dative",
                                                  "accusative"),
                                         pluralize = FALSE) {
  gender <- rlang::arg_match(gender)
  case <- rlang::arg_match(case)
  
  if (checkmate::assert_flag(pluralize)) {
    
    switch(EXPR = case,
           nominative = "die",
           genitive = "deren",
           dative = "deren",
           accusative = "die")
    
  } else {
    
    switch(EXPR = case,
           nominative = switch(EXPR = gender,
                               feminine = "die",
                               masculine = "der",
                               neuter = "das"),
           genitive = switch(EXPR = gender,
                             feminine = "deren",
                             "dessen"),
           dative = switch(EXPR = gender,
                           feminine = "der",
                           "dem"),
           accusative = switch(EXPR = gender,
                               feminine = "die",
                               masculine = "den",
                               neuter = "das"))
  }
}

#' Add the German definite article in dative case to a preposition
#'
#' @param preposition The preposition to add the German definite article in dative case to. A character scalar.
#' @param gender The grammatical gender of the `preposition`.
#'
#' @inherit definite_article_de return
#' @family spoken
#' @export
add_definite_article_de <- function(preposition,
                                    gender = c("feminine",
                                               "masculine",
                                               "neuter")) {
  checkmate::assert_string(preposition)
  gender <- rlang::arg_match(gender)
  
  if (gender == "feminine") {
    
    preposition %>% purrr::when(stringr::str_to_lower(.) == "zu" ~ paste0(., "r"),
                                ~ paste0(., " ", definite_article_de(gender = "feminine",
                                                                     case = "dative")))
  } else {
    
    preposition %>% purrr::when(stringr::str_to_lower(.) %in% c("bei", "zu") ~ paste0(., "m"),
                                stringr::str_to_lower(.) %in% c("in", "an") ~ stringr::str_replace(string = .,
                                                                                                   pattern = "n$",
                                                                                                   replacement = "m"),
                                ~ paste0(., " ", definite_article_de(gender = "masculine",
                                                                     case = "dative")))
  }
}

#' Decline a German noun
#'
#' Note that this function currently doesn't support the [special cases](https://deutsch.lingolia.com/de/grammatik/nomen/deklination/genitiv#a-besonderheiten)
#' where a masculine noun gets an `n` or `en` ending attached in the accusative, dative and genitive cases.
#'
#' @param noun The noun to decline. A character scalar.
#' @param gender The grammatical gender of the `noun`.
#' @param case The grammatical case of the `noun`.
#'
#' @inherit definite_article_de return
#' @family spoken
#' @export
decline_noun_de <- function(noun,
                            gender = c("feminine",
                                       "masculine",
                                       "neuter"),
                            case = c("nominative",
                                     "genitive",
                                     "dative",
                                     "accusative")) {
  
  gender <- rlang::arg_match(gender)
  case <- rlang::arg_match(case)
  result <- noun
  
  if (gender != "feminine" && case == "genitive") {
    
    result %<>% purrr::when(stringr::str_detect(string = ., pattern = "(ss|\U00DF|x|z)$") ~ paste0(., "es"),
                            stringr::str_detect(string = ., pattern = "s$") ~ paste0(., "ses"),
                            ~ paste0(., "s"))
  }
  
  result
}

#' Regular expression patterns and replacements for spelling normalization
#'
#' @format `r pkgsnip::return_label("data")`
#' @seealso
#' Other regular expression rules: [`yay::regex_text_normalization`] [`yay::regex_file_normalization`]
#' String normalization functions: [yay::str_normalize()] [yay::str_normalize()]
#'
#' @examples
#' # unnest the pattern column
#' salim::regex_spelling_normalization |> tidyr::unnest_longer(col = pattern)
"regex_spelling_normalization"

#' Download Pandoc release binaries
#'
#' Downloads the executable program binaries of a certain Pandoc release for Linux, macOS and Windows.
#'
#' @param os The operating systems for which Pandoc binaries should be downloaded. Any combination of
#'   `r pal::prose_ls_fn_param(param = "os", fn = download_pandoc_binaries, last_sep = " and ")`.
#' @param path The filesystem path to which the binaries are saved to. A [path][fs::fs_path] or something coercible to.
#' @param overwrite Whether to overwrite existing binaries under `path`.
#' @inheritParams pandoc_release_assets
#'
#' @return `path` invisibly.
#' @family pandoc
#' @export
download_pandoc_binaries <- function(release_id = pandoc_release_id_latest(),
                                     os = c("linux", "macos", "windows"),
                                     path = "bin/",
                                     overwrite = TRUE) {
  pal::assert_pkg("zip")
  checkmate::assert_count(release_id,
                          positive = TRUE)
  checkmate::assert_subset(os,
                           choices = eval(formals()$os),
                           empty.ok = FALSE)
  checkmate::assert_path_for_output(path,
                                    overwrite = TRUE)
  checkmate::assert_flag(overwrite)
  
  path_tmp <- fs::path_temp()
  
  assets <-
    pandoc_release_assets(release_id = release_id) %>%
    dplyr::filter(stringr::str_detect(string = filename,
                                      pattern = paste0("(?i)", pal::fuse_regex(os), "(-(amd64|x86_64))?\\.(zip|tar\\.gz)"))) %>%
    dplyr::mutate(download_path = fs::path(path_tmp, filename))
  
  # download assets to tmp dir
  purrr::walk2(.x = assets$download_url,
               .y = assets$download_path,
               .f = utils::download.file,
               method = "auto",
               mode = "wb",
               cacheOK = TRUE,
               quiet = TRUE)
  
  # extract binaries to tmp dir
  assets %>%
    dplyr::select(-download_url) %>%
    as.list() %>%
    purrr::pwalk(.f = function(filename, os, download_path) {
      
      path_os_tmp <- fs::path(path_tmp, "pandoc", os)
      
      # extract all files flat
      if (stringr::str_detect(string = filename,
                              pattern = "\\.zip$")) {
        
        zip::unzip(zipfile = download_path,
                   exdir = path_os_tmp,
                   junkpaths = TRUE)
      } else {
        
        utils::untar(tarfile = download_path,
                     exdir = path_os_tmp)
        
        # since `untar()` has no "junkpaths"-like option, we flatten the dir structure ourselves
        fs::dir_ls(path = path_os_tmp,
                   type = "file",
                   recurse = TRUE,
                   all = TRUE) %>%
          fs::file_move(new_path = path_os_tmp)
      }
      
      # delete archive and all extracted files but the Pandoc binary
      fs::file_delete(download_path)
      
      fs::dir_ls(path = path_os_tmp,
                 regexp = "[\\/]pandoc(\\.exe)?$",
                 all = TRUE,
                 invert = TRUE) %>%
        fs::file_delete()
    })
  
  # move binaries to final dir
  fs::dir_create(path = fs::path(path, "pandoc"))
  
  path_tmp %>%
    fs::path("pandoc") %T>%
    fs::dir_copy(new_path = fs::path(path, "pandoc"),
                 overwrite = overwrite) %>%
    fs::dir_delete()
  
  invisible(path)
}

#' Get latest Pandoc release ID
#'
#' Uses [gh::gh()] to fetch the latest [Pandoc](https://pandoc.org/) release ID via [GitHub's REST
#' API](https://docs.github.com/en/rest/reference/repos#get-the-latest-release).
#'
#' @return An integer scalar.
#' @family pandoc
#' @export
pandoc_release_id_latest <- function() {
  
  pal::assert_pkg("gh")
  
  gh::gh(endpoint = "/repos/{owner}/{repo}/releases/latest",
         owner = "jgm",
         repo = "pandoc",
         .method = "GET") %$%
    id
}

#' Get latest Pandoc release version number
#'
#' Uses [gh::gh()] to fetch the latest [Pandoc](https://pandoc.org/) release version number via [GitHub's REST
#' API](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) and returns it as a [numeric version][numeric_version()].
#'
#' @return `r pkgsnip::param_label("version_nr")`
#' @family pandoc
#' @export
pandoc_version_latest <- function() {
  
  pal::assert_pkg("gh")
  
  gh::gh(endpoint = "/repos/{owner}/{repo}/releases/latest",
         owner = "jgm",
         repo = "pandoc",
         .method = "GET") %$%
    name %>%
    stringr::str_extract(pattern = "\\d+(\\.\\d+)*") %>%
    as.numeric_version()
}

#' List all available Pandoc releases
#'
#' Uses [gh::gh()] to fetch all available [Pandoc](https://pandoc.org/) releases via [GitHub's REST
#' API](https://docs.github.com/en/rest/reference/repos#list-releases) and returns them as a [tibble][tibble::tbl_df] containing the two columns `version_nr`
#' and `release_id`.
#'
#' Values of the column `release_id` can be used as input to [download_pandoc_binaries()].
#'
#' @return `r pkgsnip::param_label("data")`
#' @family pandoc
#' @export
pandoc_releases <- function() {
  
  pal::assert_pkg("gh")
  
  gh::gh(endpoint = "/repos/{owner}/{repo}/releases",
         owner = "jgm",
         repo = "pandoc",
         .method = "GET",
         .limit = Inf) %>%
    purrr::map_dfr(~ tibble::tibble(version_nr =
                                      .x$name %>%
                                      stringr::str_extract(pattern = "\\d+(\\.\\d+)*") %>%
                                      as.numeric_version(),
                                    release_id = .x$id)) %>%
    dplyr::arrange(version_nr)
}

#' List Pandoc release assets
#'
#' Uses [gh::gh()] to fetch filenames, corresponding operating systems and download URLs of a specific [Pandoc](https://pandoc.org/) release via [GitHub's REST
#' API](https://docs.github.com/en/rest/reference/repos#list-release-assets) and returns them as a [tibble][tibble::tbl_df].
#'
#' @param release_id The GitHub release ID of the desired Pandoc release. Use [pandoc_releases()] to determine the release ID of a specific Pandoc version
#'   number. An integer scalar.
#'
#' @return `r pkgsnip::param_label("data")`
#' @family pandoc
#' @export
pandoc_release_assets <- function(release_id = pandoc_release_id_latest()) {
  
  pal::assert_pkg("gh")
  
  gh::gh(endpoint = "/repos/{owner}/{repo}/releases/{release_id}/assets",
         owner = "jgm",
         repo = "pandoc",
         release_id = release_id,
         .method = "GET") %>%
    purrr::map_dfr(~ tibble::tibble(filename = .x$name,
                                    os =
                                      .x$name %>%
                                      stringr::str_extract(pattern = "(?i)(linux|macos|windows|\\.deb$)") %>%
                                      stringr::str_to_lower() %>%
                                      stringr::str_replace(pattern = "\\.deb",
                                                           replacement = "linux"),
                                    download_url = .x$browser_download_url))
}

#' Level up R
#'
#' Checks whether the installed R version is >= a cached reference version. Intended to level up the R version in use between multiple users of the same code
#' (e.g. contributors to a specific R project).
#'
#' If the file `path_min_vrsn` exists, it is checked whether the installed R version is greater than or equal to the version number stored in that file, and if
#' not, an alert is displayed.
#' 
#' If `update_min_vrsn` is set to `TRUE` and the file `path_min_vrsn` doesn't exist or contains an R version string that's lower than the currently installed
#' version of R, `path_min_vrsn` is overwritten with the currently installed R version string.
#'
#' @param path_min_vrsn Path to the cached R version string.
#' @param update_min_vrsn Whether or not to overwrite `path_min_vrsn` with the currently installed R version string *iff* the latter is higher than the former.
#'
#' @return Currently installed R version as a [numeric version][as.package_version], invisibly.
#' @family dev_env
#' @export
lvl_up_r <- function(path_min_vrsn,
                     update_min_vrsn = FALSE) {
  
  checkmate::assert_flag(update_min_vrsn)
  
  if (fs::file_exists(path_min_vrsn)) {
    
    min_vrsn <-
      path_min_vrsn %>%
      brio::read_lines(n = 1L) %>%
      as.package_version()
    
  } else {
    min_vrsn <- as.package_version("0.0")
  }
  
  current_vrsn <-
    R.Version() %$%
    glue::glue("{major}.{minor}") %>%
    as.package_version()
  
  if (isTRUE(current_vrsn < min_vrsn)) {
    
    cli::cli_alert_warning(paste0(
      "Your version of {.pkg R} is out of date. Please update to version {.val {min_vrsn}} or above. The latest stable release is available at ",
      "{.url https://cloud.r-project.org/}.", pkg_mgr_hint("R")
    ))
  }
  
  if (update_min_vrsn && current_vrsn > min_vrsn) {
    
    brio::write_lines(text = current_vrsn,
                      path = path_min_vrsn)
  }
  
  invisible(current_vrsn)
}

#' Level up RStudio
#'
#' Checks whether the currently running [RStudio](https://rstudio.com/products/rstudio/) version is >= a cached reference version. Intended to level up the 
#' RStudio version in use between multiple users of the same code (e.g. contributors to a specific R project).
#'
#' If the file `path_min_vrsn` exists, it is checked whether RStudio is running, and if so, whether its version number is greater than or equal to the version
#' number stored in that file. If this is not the case, an alert is displayed.
#' 
#' If `update_min_vrsn` is set to `TRUE` and the file `path_min_vrsn` doesn't exist or contains an RStudio version string that's lower than the currently
#' running version of RStudio, `path_min_vrsn` is overwritten with the currently running RStudio version string.
#'
#' Note that since **RStudio must be running for `lvl_up_rstudio()` to have any effect**, it can't be directly called in a (project-level)
#' [`.Rprofile`](https://support.rstudio.com/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf)
#' startup script. Instead, the [`rstudio.sessionInit`](https://docs.rstudio.com/ide/server-pro/r_sessions/session_startup_scripts.html) hook can be used.
#' Example:
#' 
#' ```r
#' setHook(hookName = "rstudio.sessionInit",
#'         value = function(newSession) {
#'             if (newSession)
#'                 salim::lvl_up_rstudio(path_min_vrsn = ".RStudio_version",
#'                                       update_min_vrsn = TRUE)
#'         },
#'         action = "append")
#' ```
#'
#' @param path_min_vrsn Path to the cached RStudio version string.
#' @param update_min_vrsn Whether or not to overwrite `path_min_vrsn` with the currently running RStudio version string *iff* the latter is higher than the
#'   former.
#'
#' @return Currently running RStudio version as a [numeric version][as.package_version], or `NULL` if RStudio is not running, invisibly.
#' @family dev_env
#' @export
lvl_up_rstudio <- function(path_min_vrsn,
                           update_min_vrsn = FALSE) {
  
  checkmate::assert_flag(update_min_vrsn)
  pal::assert_pkg("rstudioapi")
  current_vrsn <- NULL
  
  # skip if RStudio is not running
  if (rstudioapi::isAvailable()) {
    
    if (fs::file_exists(path_min_vrsn)) {
      
      min_vrsn <-
        path_min_vrsn %>%
        brio::read_lines(n = 1L) %>%
        as.package_version()
      
    } else {
      min_vrsn <- as.package_version("0.0")
    }
    
    current_vrsn <-
      rstudioapi::versionInfo() %>%
      purrr::chuck("version")
    
    if (isTRUE(current_vrsn < min_vrsn)) {
      
      cli::cli_alert_warning(paste0(
        "Your version of {.pkg RStudio} is out of date. Please update to version {.val {min_vrsn}} or above. The latest version is available at ",
        "{.url https://rstudio.com/products/rstudio/download/#download}.", pkg_mgr_hint("RStudio")
      ))
    }
    
    if (update_min_vrsn && current_vrsn > min_vrsn) {
      
      brio::write_lines(text = current_vrsn,
                        path = path_min_vrsn)
    }
  }
  
  invisible(current_vrsn)
}

#' Level up Quarto
#'
#' Checks whether the installed [Quarto](https://quarto.org/) version is >= a cached reference version. Intended to level up the Quarto version in use between
#' multiple users of the same code (e.g. contributors to a specific Quarto project).
#'
#' @param path_min_vrsn Path to the cached Quarto version string.
#' @param update_min_vrsn Whether or not to overwrite `path_min_vrsn` with the currently installed Quarto version string *iff* the latter is higher than the
#'   former.
#'
#' @return Currently installed Quarto version as a [numeric version][numeric_version], invisibly.
#' @family dev_env
#' @export
lvl_up_quarto <- function(path_min_vrsn,
                          update_min_vrsn = FALSE) {
  
  checkmate::assert_flag(update_min_vrsn)
  pal::assert_pkg("quarto")
  
  if (fs::file_exists(path_min_vrsn)) {
    
    min_vrsn <-
      path_min_vrsn %>%
      brio::read_lines(n = 1L) %>%
      as.package_version()
    
  } else {
    min_vrsn <- as.package_version("0.0")
  }
  
  current_vrsn <-
    quarto::quarto_path() %>%
    system2(args = "--version",
            stdout = TRUE,
            stderr = TRUE) %>%
    as.package_version()
  
  if (isTRUE(current_vrsn < min_vrsn)) {
    
    cli::cli_alert_warning(paste0(
      "Your version of {.pkg Quarto} is out of date. Please update to version {.val {min_vrsn}} or above. The latest stable release is available at ",
      "{.url https://quarto.org/docs/get-started/}.", pkg_mgr_hint("Quarto")
    ))
  }
  
  if (update_min_vrsn && current_vrsn > min_vrsn) {
    
    brio::write_lines(text = current_vrsn,
                      path = path_min_vrsn)
  }
  
  invisible(current_vrsn)
}

#' Update [Salim B's R packages](https://gitlab.com/salim_b/r/pkgs)
#'
#' Updates all of [Salim B's R packages](https://gitlab.com/salim_b/r/pkgs) to the latest development version.
#'
#' @param pkgs The R pkgs to be updated. A subset of:
#'   `r pal::prose_ls_fn_param(fn = "update_salims_pkgs", param = "pkgs", last_sep = " and ", as_scalar = FALSE) %>% pal::as_md_list()`
#'
#' @return `pkgs`, invisibly.
#' @family dev_env
#' @export
update_salims_pkgs <- function(pkgs = c("c2d4u",
                                        "pal",
                                        "pkgpins",
                                        "pkgpurl",
                                        "pkgsnip",
                                        "qstnr",
                                        "rstd",
                                        "salim",
                                        "swissmuni",
                                        "swissparty",
                                        "tocr",
                                        "yay")) {
  pal::assert_pkg("remotes")
  
  checkmate::assert_subset(x = pkgs,
                           choices = as.character(formals()$pkgs)) %>%
    purrr::walk(~ {
      
      if (pal::is_pkg_cran(.x)) {
        utils::install.packages(pkgs = .x,
                                repos = "https://cloud.r-project.org/")
      } else {
        remotes::install_gitlab(repo = paste0("salim_b/r/pkgs/", .x),
                                upgrade = FALSE)
      }
    })
  
  invisible(pkgs)
}
